export const GET_CLASSROOMS = "GET_CLASSROOMS";
export const CLASSROOMS_LOADING = "CLASSROOMS_LOADING";
export const GET_CLASSROOM_OBJ = "GET_CLASSROOM_OBJ";
export const CREATE_CLASSROOM = "CREATE_CLASSROOM";
export const UPDARE_CLASSROOM = "UPDARE_CLASSROOM";
export const REMOVE_CLASSROOM = "REMOVE_CLASSROOM";
